"""add firmware_update_cache table

Revision ID: a1b2c3d4e5f6
Revises: 8ac4141a98c6
Create Date: 2025-12-30 12:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '8ac4141a98c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'firmware_update_cache',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('printer_id', sa.String(length=36), nullable=False),
        sa.Column('rollout_id', sa.Integer(), nullable=False),
        sa.Column('firmware_version', sa.String(length=16), nullable=False),
        sa.Column('platform', sa.String(length=32), nullable=False),
        sa.Column('channel', sa.String(length=16), nullable=False),
        sa.Column('md5_checksum', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_delivered', sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(['rollout_id'], ['update_rollouts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmware_update_cache_channel'), 'firmware_update_cache', ['channel'], unique=False)
    op.create_index(op.f('ix_firmware_update_cache_firmware_version'), 'firmware_update_cache', ['firmware_version'], unique=False)
    op.create_index(op.f('ix_firmware_update_cache_is_delivered'), 'firmware_update_cache', ['is_delivered'], unique=False)
    op.create_index(op.f('ix_firmware_update_cache_printer_id'), 'firmware_update_cache', ['printer_id'], unique=False)
    op.create_index(op.f('ix_firmware_update_cache_platform'), 'firmware_update_cache', ['platform'], unique=False)
    op.create_index(op.f('ix_firmware_update_cache_rollout_id'), 'firmware_update_cache', ['rollout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firmware_update_cache_rollout_id'), table_name='firmware_update_cache')
    op.drop_index(op.f('ix_firmware_update_cache_platform'), table_name='firmware_update_cache')
    op.drop_index(op.f('ix_firmware_update_cache_printer_id'), table_name='firmware_update_cache')
    op.drop_index(op.f('ix_firmware_update_cache_is_delivered'), table_name='firmware_update_cache')
    op.drop_index(op.f('ix_firmware_update_cache_firmware_version'), table_name='firmware_update_cache')
    op.drop_index(op.f('ix_firmware_update_cache_channel'), table_name='firmware_update_cache')
    op.drop_table('firmware_update_cache')
    # ### end Alembic commands ###
