"""Fix messagelog fk to reference printers

Revision ID: 97969ba2b14e
Revises: 001_initial_schema
Create Date: 2025-12-27 18:45:02.099526+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97969ba2b14e'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firmware_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firmware_versions_id'))

    with op.batch_alter_table('group_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_memberships_id'))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_id'))

    with op.batch_alter_table('message_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_cache_id'))

    with op.batch_alter_table('message_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_logs_id'))
        batch_op.drop_constraint(batch_op.f('message_logs_recipient_uuid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'printers', ['recipient_uuid'], ['uuid'])

    with op.batch_alter_table('printer_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_printer_groups_id'))

    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_printers_id'))

    with op.batch_alter_table('update_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_update_history_id'))

    with op.batch_alter_table('update_rollouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_update_rollouts_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    with op.batch_alter_table('update_rollouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_update_rollouts_id'), ['id'], unique=False)

    with op.batch_alter_table('update_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_update_history_id'), ['id'], unique=False)

    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_printers_id'), ['id'], unique=False)

    with op.batch_alter_table('printer_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_printer_groups_id'), ['id'], unique=False)

    with op.batch_alter_table('message_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('message_logs_recipient_uuid_fkey'), 'users', ['recipient_uuid'], ['uuid'])
        batch_op.create_index(batch_op.f('ix_message_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('message_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_cache_id'), ['id'], unique=False)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_id'), ['id'], unique=False)

    with op.batch_alter_table('group_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_memberships_id'), ['id'], unique=False)

    with op.batch_alter_table('firmware_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firmware_versions_id'), ['id'], unique=False)

    # ### end Alembic commands ###
