"""add channel to update_rollouts

Revision ID: 8ac4141a98c6
Revises: 97969ba2b14e
Create Date: 2025-12-28 11:19:08.485259+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ac4141a98c6'
down_revision: Union[str, None] = '97969ba2b14e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_rollouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(length=16), server_default=sa.text("'stable'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_rollouts', schema=None) as batch_op:
        batch_op.drop_column('channel')

    # ### end Alembic commands ###
